### ISSUE TITLE
DirtyCredの問題ファイルがリンク切れしている

### ISSUE THREAD

**Issue by rqdaA** [smallkirby/p3land#4]
[DirtyCred](https://p3land.smallkirby.com/kernel/dirtycred/)の問題リンクが404ページを返しており、問題に取り組めない状態になっています。vmlinuxについては問題なくダウンロードできます。

お手数をおかけしますがご対応よろしくお願いします。

**Comment by smallkirby** [comment]
@rqdaA 
リンク切れを修正しました！ :pray:

**Comment by rqdaA** [comment]
ありがとうございます！
